<?php
// Plugin definition
$plugin = array(
  'title' => t('mothership-prototype'),
  'category' => t('Mothership'),
  'icon' =>  'mothership-prototype.png',
  'theme' => 'mothership-prototype',
  'css' => 'mothership-prototype.admin.css',
  'regions' => array(
    'content-1' => t('content-1'),
    'content-2' => t('content-2'),
    'content-3' => t('content-3'),
    'content-4' => t('content-4'),
  ),
);
